# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: econtrer <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/21 20:46:48 by econtrer          #+#    #+#              #
#    Updated: 2019/07/21 21:51:03 by econtrer         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = rush-02

SRC = main.c ft1.c ft2.c read.c pdict.c

all: $(NAME)

$(NAME): fclean
	gcc -Wall -Wextra -Werror -o $(NAME) $(SRC)

fclean:
	rm -f $(NAME)

